### ISSUE TITLE
Now datetime field

### ISSUE THREAD

**Issue by jmgirven** [alfred82santa/dirty-models#100]
It might be a nice addition to allow a `DateTimeField` field to default to `datetime.now()`. If I do e.g:

```
class TestModel(BaseModel):
    created = DateTimeField(default=datetime.now())

a = TestModel()
b = TestModel()

a.created == b.created  # True
```

Which I wouldn't expect. Obviously it is trivial to give `now` to the model creation instead.

A more generic way would be to add a `default_f` argument to `BaseField` which takes a function that is run when the model is created. See this [no longer maintained similar project](https://github.com/jeffjenkins/MongoAlchemy/blob/f1ee35a0856212a11f73ba561bb3344662ca3524/mongoalchemy/fields/base.py#L143).

**Comment by alfred82santa** [comment]
I like the idea. Is it something like a default value factory?

**Comment by jmgirven** [comment]
Exactly.

**Comment by alfred82santa** [comment]
I'm thinking how to implement it. I'm sure I'm not going to add a new param. I guess we don't need it. I could check if it is `callable` in order to know whether it is a factory or not.

On the other hand, it looks like it will be complex to implement just for default values. Default values are a little bit more complicate I like to confess. There are different ways to define default values in order to allow developer to override inherited default values or embedded/children models default values.

So, I'm thinking to implement it as a regular type casting. As collateral effect, it would allow things like this:

```
class MyModel(BaseModel):
    foo = DateTimeField()

bar = MyModel()
bar.foo = datetime.now
print(bar.foo)
# 2017-11-02 19:54:40.180772
```

**Comment by alfred82santa** [comment]
New version published with factory feature.
https://github.com/alfred82santa/dirty-models#version-0101
