### ISSUE TITLE
Required attribute for field

### ISSUE THREAD

**Issue by jmgirven** [alfred82santa/dirty-models#99]
Is it possible to mark a field as required? I.e. when constructing the object this field **must** be set. Similarly you would not be able to set the field to `None` to remove it's value.

**Comment by alfred82santa** [comment]
No, it is not possible. There isn't any validation in models. The reason is because I develop other library in order to run model validations: https://github.com/alfred82santa/dirty-validators
I'm not sure whether it is what you need. But when you define a model validation you could use a Required validator.

**Comment by jmgirven** [comment]
Ah OK, I hadn't found that. So, if I had a model like:

```
class TestModel(BaseModel):
    atest = StringField()
```

Would I use `dirty-validators`  something like:

```
class TestModelValidate(ModelValidate):
    __modelclass__ = TestModel
    atest = Required()
```

to e.g. throw an error if `TestModel` is instantiated without `atest` being set?

**Comment by alfred82santa** [comment]
Your code is fine.
But it does not raise an exception, method `is_valid` returns `False` when object does not pass validations. You could get errors from `messages` property.

**Comment by alfred82santa** [comment]
I'm going to close this issue. If you need more help about dirty-validator I think it is better to open a new issue in its repo.
